/**
 * 
 */
package com.string.naive;

/**
 * @author 		Manjusri Ishwara
 * @date		Jan 26, 2014 - 8:01:23 PM
 * @type        Check
 *
 */
public class Check {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		String s = "LJFCLEBNHOVZZQGLBNHOVVRXLIPKXNNKSFNC" +
				"GLLEBNHOUXNKRWCGALERVVOUILLIUOBKCNNKWRDIANKWSGQZZSERULBNVUODLMCNMBHKWRDKC" +
				"SGOVKDIALLJFCLASQLUXLKNNJGALLEBNHOUAFCNHOVVRVIAQFSZWNCNMXLIOVVTEOXLKNNKSF" +
				"NDLERWCGALERVVOVIAMXLIQGLBNHOUAFCLBNHOWNCLIQGLBNHPKNNJGALLEBNHOUBWMOTUVOW" +
				"RDIALLIUOBJZSZZQHOVVRWKNNJXLKNMBNWCGANCGMALMDEKNNKRVVXNKRVVPHRDJZXMDLVWRB" +
				"NMBXLIOVWRBNMBHILMXLIOVWRBNMALNNCQSNWDVVOUILLJFDEKNMALLIVKDXLIQGLBNHOUAFC" +
				"LAFNNHDLERVVOWRDIANJGALLASQLVVRVIBKCLIUOBKCNNKWRDIANKWSGQZZSFNDLERVVXLKNN" +
				"KSFNDLFNCHDLERWCHDULANKSERVUODLLARXNKSETILLJFCNNGMBHILLIOWNCLIXLIOVVXLIPK" +
				"NNKSFNXNKSFNDLERWCGALERVVXLIOVWRBNMALLBMDEKNNKWRDIANKVKCSXLIOXLKNMALLIOWN" +
				"DLVVTEXLIPKNNKSFNDLERWDXNKRWCGALERVVOUILLIUQFSZZQGLBNHOVUVQWWTZVVRVIAQFRV" +
				"KCNNKVJZQUQSNWCGANCGLMDEIOVVRWKNNKWRDIANKWSGQZZSFNCGLLXLIOUBZQGLBNHOUAFCN" +
				"HOVVRVKCLIZSXNKTIMBNWCGALERULXLIOVWRBNMBHILLJFCNNCQSXNKSERXLIPKNMALMDLWNC" +
				"LIQGLAFNMBHXLIOXLIOXLIXLIXLIXLIXLKNNKRVVOXLIPKNNKSFNCGLLEBNHOUAFCLAFNMBHK" +
				"TILMXLIOVXLIPKNMXLIOVVRWKNNKWRDIANKWSGOVIAXLKNNKRVWWRBNMBHKWSGOVIAXLIPKNN" +
				"KRULBNVVOWRDIALLIUOBKCLIUQFRVKCLIZSZWNCNNKSFNDLERWCGANCGLMDEKNNKXLKNNKRVX" +
				"KWSGQWZWNCNNKRWXLIPKNNKSFNDLERWCGANCGLLEBNHOWNCNMBNZSETXLIQHPKNNJGALMDEKN" +
				"NKRVXNKRVVOUJGXLIQGLBNHOUAFCNHOVVRVXLKNNKSFNDLERWCGALERVVOUILLIUOBJZSZWNC" +
				"NNKSERVVOVKCSGOVIANKWSGOVIALLIVKCLJFCNNDMBHKWSGPXLIQGLAFNNHDLERULXLIQHOWN" +
				"CMCNMBNWCGALERUXLJFCNMBHKRVWXLIOVVTEXLIOVUUQSNWCGANDLERVVOVIANKWRDIALLIUO" +
				"AQFSZZQGLAFMDEIOVUUQSMROCQSNVWZZXLIOUAFCNHOVVRVKCLIZRWJFCNNDMBHKWSGQZWCGB" +
				"HDWCXLKNNJGANHDLERULANKRVWWSQXMDLUAFCLAEBNGLAFNLMDEKNMBMRODLLBNMBHILLIVIX" +
				"LIQGLXNJGANHDLERWCGALERVVOVKDIALLIUQFSZZQGLBNHOVWSQNDLUAFCNHOWNCLIQGLAFMD" +
				"EKNNKRVUQSNULANKSFNDLFNCGLLEAEBNHOWNCLIOVVRWKNMBKCSGOVIALMDIBIBJUOAQFRVKC" +
				"LJFCNXMBNVVOVXLKNNKRVVOWSGOUILLJFCNNDMBHXLIPKNNKSFNDLERWCGBGANCGLLEBNHOUA" +
				"FCNHOVVRWKNNKWSGOVIANKWRDIANKWSGQZULANKSERULANKSERULANKSFNDLXNKSFNCGMBHIL" +
				"LIOWNCLIQHOWNCLIQHOWNCLIQGLXLJFCLEBNHOVVRVIAQFRVKCNNKZQUOXLKNNKRVVOVXLJFC" +
				"NNHDLERVVOVXLIOXNKRVVOUJGAXNKRVVOUILLJFCLASQLVVXLIOVVR";
				
		String p = "L";
		
		NaiveStringMatching nv = new NaiveStringMatching(s, p);
		nv.count();
	}

}
